[package]
authors = ["Brayden Banks <bb010g@gmail.com>"]
build = "build.rs"
description = "ISO 4217–compliant currency library"
license = "MIT"
name = "penny"
readme = "README.md"
repository = "https://github.com/bb010g/penny"
version = "0.2.0"

[build-dependencies]
phf_codegen = "0.7.21"
quick-xml = "0.7.0"

[dependencies]
phf = "0.7.21"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.serde]
optional = true
version = "1.0.8"

[dependencies.serde_derive]
optional = true
version = "1.0.8"

[features]
default = []
lint = ["clippy"]
serde-serialize = ["serde", "serde_derive"]
